### ISSUE TITLE
[REQUEST] Show lowest and largest number

### ISSUE THREAD

**Issue by Mobilpadde** [gribnoysup/wunderbar#1]
Would be pretty useful, if the inputs are below 0, it'd show the lowest and largest number on the scale and in legend. :100: 

Right now, it only shows 0.00, but I'm working with numebrs like 0.0000001. :cactus:

**Comment by gribnoysup** [comment]
Hi @Mobilpadde! Yep, this sounds like a good idea! 

Are you using this library programmatically or directly from the terminal? What are your min-max values? Can you provide a small sample of data you want to print so I can check it locally? 

I am thinking of adding something like `format` method to options that will just do `value.toFixed(2)` by default and then you can provide a custom method ([`numeral.format`](http://numeraljs.com/#format) for example) to format the value however you want. Maybe we can even use this library internally to allow formatting from the terminal 🤔

What do you think? Would that solve your issue?

**Comment by Mobilpadde** [comment]
I'm using it programmatically, using the data from the [nicehash-api](https://api.nicehash.com/api?method=stats.provider&addr=3R1rHrukxwSEBufNZQ7KX1Skkroz3U9yLr). As you see, it's some quite small values. :laughing: But I'd love a format thingie :smile_cat:

**Comment by gribnoysup** [comment]
Hey @Mobilpadde! I just published #2 as a prerelease. Can you try it in your application? You can install it with `npm i -s @gribnoysup/wunderbar@next`

In this version, you get a `format` option that can be a string, matching one of the [Numeral.js formats](http://numeraljs.com/#format) or a function that gets the bar value as a first argument, and returns a string.

Does that solve your problem?

**Comment by gribnoysup** [comment]
Fixed in `v1.1.1`
