### ISSUE TITLE
Configurable colors

### ISSUE THREAD

**Issue by ericman314** [gribnoysup/wunderbar#9]
I would like to be able to explicitly set the hex value or name of the color for each data value, is that possible?

**Comment by gribnoysup** [comment]
Hi @ericman314! Yeah, you can provide color for each data value:

```js
wunderbar([{ value: 1, color: 'red' }, { value: 2, color: '#0f0' }])
```

Input value type is documented here: https://github.com/gribnoysup/wunderbar#types

**Comment by ericman314** [comment]
Thanks! Completely missed that....
